=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIPSTR1/testCase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:element name="testCase">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="references"/>
        <xs:element ref="requirementText"/>
        <xs:element ref="description"/>
        <xs:element ref="dependencies"/>
        <xs:element ref="rules"/>
      </xs:sequence>
      <xs:attribute name="testable" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="FALSE"/>
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="UNKNOWN"/>
            <xs:enumeration value="PARTIAL"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="id">
    <xs:complexType>
      <xs:attribute name="requirementId" use="required" type="xs:NCName"/>
      <xs:attribute name="specification" use="required"/>
      <xs:attribute name="version" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="references">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="reference" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="reference">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              reference (element text): Requirement text copied from the specification.
            </xs:documentation>
          </xs:annotation>
          <xs:attribute name="requirementId" use="required" type="xs:NCName">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @requirementId: Short ID of the requirement, as defined in the specification, e.g. CSIP1, CSIPSTR5.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="URL" use="required" type="xs:anyURI">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @URL: Direct URL to the requirement text in the specification.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="requirementText">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="name" type="xs:string" minOccurs="0"/>
        <xs:element name="location" type="xs:string" minOccurs="0"/>
        <xs:element name="description" type="xs:string" minOccurs="0"/>
        <xs:element name="cardinality" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="0..1"/>
              <xs:enumeration value="0..n"/>
              <xs:enumeration value="1..1"/>
              <xs:enumeration value="1..n"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="level" minOccurs="0">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="MUST"/>
              <xs:enumeration value="SHOULD"/>
              <xs:enumeration value="MAY"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="dependencies">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dependency" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="dependency">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:annotation>
            <xs:documentation xml:lang="en">
              dependency (element text): Description of the dependency.
            </xs:documentation>
          </xs:annotation>
          <xs:attribute name="requirementId" use="required" type="xs:NCName">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @requirementId: Short ID of the requirement, as defined in the specification, e.g. CSIP1, CSIPSTR5.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:attribute name="URL" use="required" type="xs:anyURI">
            <xs:annotation>
              <xs:documentation xml:lang="en">
                @URL: Direct URL to the requirement text in the specification.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="rules">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="rule"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="rule">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="description"/>
        <xs:element ref="error"/>
        <xs:element ref="corpusPackages"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="error">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="message"/>
      </xs:sequence>
      <xs:attribute name="level" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="ERROR"/>
            <xs:enumeration value="WARNING"/>
            <xs:enumeration value="INFO"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="message" type="xs:string"/>
  <xs:element name="corpusPackages">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="package" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="package">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="path"/>
        <xs:element ref="description"/>
      </xs:sequence>
      <xs:attribute name="isValid" use="required">
        <xs:annotation>
          <xs:documentation xml:lang="en">
          The isValid attribute should be set TRUE for corpus packages that
          shouldn't generate any validation messages, including WARNING or INFO
          messages. The attribute is inappropriately named but changing it would
          break too many existing test cases.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="isImplemented" use="optional" default="FALSE">
        <xs:annotation>
          <xs:documentation xml:lang="en">
          The isImplemented attribute should be set FALSE for corpus packages that
          are defined in the test case but not implemented as a package. The attribute
          is optional and defaults to TRUE.
          </xs:documentation>
        </xs:annotation>
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="TRUE"/>
            <xs:enumeration value="FALSE"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="path" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
</xs:schema>

=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIP99/testCase.xml
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd"
  testable="FALSE">
    <id specification="E-ARK CSIP" version="2.0.4" requirementId="CSIP99"/>
    <references>
    <reference requirementId="CSIP99" URL="https://earkcsip.dilcis.eu/#CSIP99"/>
  </references>
  <requirementText>
    <name>Schema division label</name>
    <location>mets/structMap[@LABEL='CSIP']/div/div[@LABEL='Schemas']</location>
    <description>
      The schema division div element's @LABEL attribute has the value "Schemas" from the vocabulary.
      See also: File group names
    </description>
    <cardinality>1..1</cardinality>
    <level>MUST</level>
  </requirementText>
  <description>
    CSIP99 seems identical to CSIP97, but the authors of the specification
    had a distinction in mind: "â€¦ the first requirement defines whether the
    division itself is mandatory, the second defines the required label
    value," see the issue "Redundancies and incompatible priority levels" at
    https://github.com/DILCISBoard/E-ARK-CSIP/issues/570. The cases of there
    being no schema division or more than one schema division
    are handled in CSIP97. Consequently, there is only one rule left for
    CSIP99:
      If the schema division exists, it MUST have @LABEL='Schemas'.

    This, however, is not reliably testable with algorithms of reasonable
    complexity. Detecting a schema division that is not marked
    @LABEL='Schemas' would require analysing indirect indicators (e.g. a
    structMap/div with references to files in a folder named "schemas"), but
    these cannot give enough confidence to announce a violation of a MUST
    rule.

    In sum, only valid IPs are meaningful for CSIP99 and the requirement is
    effectively not testable.
  </description>
  <dependencies>
    <dependency requirementId="CSIP97" URL="https://earkcsip.dilcis.eu/#CSIP97"></dependency>
  </dependencies>
  <rules>
    <rule id="1">
      <description>If the schema division exists, it MUST have @LABEL='Schemas'.</description>
      <error level="ERROR">
        <message>If the schema division exists, it MUST have @LABEL='Schemas'.</message>
      </error>
      <corpusPackages>
        <package isValid="TRUE" isImplemented="TRUE" name="minimal_IP_with_1_representation">
          <path>valid/minimal_IP_with_1_representation</path>
          <description>Minimal IP</description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIP63/testCase.xml
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd" testable="TRUE">
  <id specification="CSIP" version="2.0.4" requirementId="CSIP63"/>
  <references>
    <reference requirementId="CSIP63" URL="https://earkcsip.dilcis.eu/#CSIP63"/>
  </references>
  <requirementText>
      <name>Other Content Information Type Specification</name>
      <location>mets/fileSec/fileGrp[@csip:CONTENTINFORMATIONTYPE='OTHER']/@csip:OTHERCONTENTINFORMATIONTYPE</location>
    <description>
      When the mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE has the value "OTHER" the mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE must state a value for the Content Information Type Specification used.
    </description>
    <cardinality>0..1</cardinality>
    <!--  It is actually a MUST or more precisely, a "conditional MUST":
          if mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER" then
          mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE MUST be used. -->
    <level>MAY</level>
  </requirementText>
  <description>
    If mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER" then mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE:
    - MUST exist;
    - MUST have a string value declaring the content information type of the fileGrp;
    - MUST NOT have a value from the VocabularyContentInformationTypeSpecification because these vocabulary values MUST be used for the attribute mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE.
    If mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE exists then mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE MUST be "OTHER".
  </description>
  <dependencies>
    <dependency requirementId="CSIP62" URL="https://earkcsip.dilcis.eu/#CSIP62">
      The value of CSIP62 determines the existence of this attribute.
    </dependency>
    <dependency requirementId="VocabularyContentInformationTypeSpecification" URL="https://earkcsip.dilcis.eu/schema/CSIPVocabularyContentInformationType.xml">
      The value of the attribute MUST NOT be from the vocabulary.
    </dependency>
  </dependencies>
  <rules>
    <rule id="1">
      <description>If mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER" then mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE MUST exist.</description>
      <error level="ERROR">
        <message>
          mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE attribute does not exist. MUST be: If mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER" then mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE MUST exist and have a value.
        </message>
      </error>
      <corpusPackages>
        <package name="CONTENTINFORMATIONTYPE_OTHER_and_OTHERCONTENTINFORMATIONTYPE_not_exist" isValid="FALSE" isImplemented="TRUE">
          <path>invalid/CONTENTINFORMATIONTYPE_OTHER_and_OTHERCONTENTINFORMATIONTYPE_not_exist</path>
          <description>
            METS.xml file where:
            - mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER",
            - mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE attribute does not exist.
          </description>
        </package>
        <package name="valid_IP_with_SHOULD_MAY_1" isValid="TRUE" isImplemented="TRUE">
          <path>valid/valid_IP_with_SHOULD_MAY_1_rep</path>
          <description>
            Minimal IP that matches all MUST requirements, mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER", mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE = "Custom CITS".
          </description>
        </package>
      </corpusPackages>
    </rule>
    <rule id="2">
      <description>If mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER" then mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE MUST exist and have a value.</description>
      <error level="ERROR">
        <message>
          mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE attribute has no value. MUST be: If mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER" then mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE MUST exist and have a value.
        </message>
      </error>
      <corpusPackages>
        <package name="CONTENTINFORMATIONTYPE_OTHER_and_OTHERCONTENTINFORMATIONTYPE_no_value" isValid="FALSE" isImplemented="TRUE">
          <path>invalid/CONTENTINFORMATIONTYPE_OTHER_and_OTHERCONTENTINFORMATIONTYPE_no_value</path>
          <description>
            METS.xml file where:
            - mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER",
            - mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE = "".
          </description>
        </package>
        <package name="valid_IP_with_SHOULD_MAY_1_rep" isValid="TRUE" isImplemented="TRUE">
          <path>valid/valid_IP_with_SHOULD_MAY_1_rep</path>
          <description>
            Minimal IP that matches all MUST requirements, mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER", mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE = "Custom CITS".
          </description>
        </package>
      </corpusPackages>
    </rule>
    <!-- This rule is implicit in the specification and is important for CSIP62 and CSIP63 to work as intended. -->
    <rule id="3">
      <description>If mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER" then mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE MUST NOT have a value from the VocabularyContentInformationTypeSpecification because these vocabulary values MUST be used for the attribute mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE.</description>
      <error level="ERROR">
        <message>
          mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE attribute has a value that MUST instead be used for mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE. MUST be: mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE MUST describe a content information type that falls outside of the VocabularyContentInformationTypeSpecification vocabulary.
        </message>
      </error>
      <corpusPackages>
        <!-- Ideally, there should be an invalid IP for each specific vocabulary
          value, as this is the only certain way to test that the validator
          checks for all of them. This should be automated as
          VocabularyContentInformationTypeSpecification currently allows 7 different values. -->
        <package name="CONTENTINFORMATIONTYPE_OTHER_and_OTHERCONTENTINFORMATIONTYPE_vocabulary_1" isValid="FALSE" isImplemented="TRUE">
          <path>invalid/CONTENTINFORMATIONTYPE_OTHER_and_OTHERCONTENTINFORMATIONTYPE_vocabulary_1</path>
          <description>
            METS.xml file has mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER", mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE = "ERMS".
          </description>
        </package>
        <package name="valid_IP_with_SHOULD_MAY_1_rep" isValid="TRUE" isImplemented="TRUE">
          <path>valid/valid_IP_with_SHOULD_MAY_1_rep</path>
          <description>
            Minimal IP that matches all MUST requirements, mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER", mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE = "Custom CITS".
          </description>
        </package>
      </corpusPackages>
    </rule>
    <!-- This rule is implicit in the specification and is important for CSIP62 and CSIP63 to work as intended. -->
    <rule id="4">
      <description>If mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE exists then mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE MUST be "OTHER".</description>
      <error level="ERROR">
        <message>
          mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE exists although mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE is not "OTHER". MUST be: mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE MUST only exist if mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER".
        </message>
      </error>
      <corpusPackages>
        <package name="CONTENTINFORMATIONTYPE_not_OTHER_and_OTHERCONTENTINFORMATIONTYPE_exists" isValid="FALSE" isImplemented="TRUE">
          <path>invalid/CONTENTINFORMATIONTYPE_not_OTHER_and_OTHERCONTENTINFORMATIONTYPE_exists</path>
          <description>
            METS.xml file has mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "ERMS" and mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE = "Custom CITS".
          </description>
        </package>
        <package name="valid_IP_with_SHOULD_MAY_1_rep" isValid="TRUE" isImplemented="TRUE">
          <path>valid/valid_IP_with_SHOULD_MAY_1_rep</path>
          <description>
            Minimal IP that matches all MUST requirements, mets/fileSec/fileGrp/@csip:CONTENTINFORMATIONTYPE = "OTHER", mets/fileSec/fileGrp/@csip:OTHERCONTENTINFORMATIONTYPE = "Custom CITS".
          </description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIP22/testCase.xml
<!-- Root element for an individual test case, allows these to be wrapped into
XML lists -->
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd"
  testable="TRUE">
  <!-- Unique ID for the test case -->
  <id specification="E-ARK CSIP" version="2.1.0" requirementId="CSIP22"/>
  <!-- URL references to requirements for convenient lookup -->
  <references>
    <reference requirementId="CSIP22" URL="http://earkcsip.dilcis.eu/#CSIP22"/>
  </references>
  <!-- The full text of the requirement. -->
  <requirementText>The locator type is always used with the value "URL" from the vocabulary in the attribute.
</requirementText>
  <!-- Textual description of the test case, extra notes beyond the requirment text. -->
  <description>The attribute LOCTYPE is mandatory in the METS-standard, and there are 7 possible values. Only the value "URL" is valid. Therefore we should create corpus packages with one or all of the other 6 values.</description>
  <!-- List of requirments that this test case depends on in addition to the
  main requirememt, e.g. general requirments on the form of IDs -->
  <dependencies>
  </dependencies>
  <!-- A list of the validation rules derived from the test case -->
  <rules>
    <rule id="1">
      <description>The LOCTYPE-attribute must always have the value "URL".</description>
      <error level="ERROR">
        <message>The LOCTYPE-attribute does not have the value "URL". The LOCTYPE-attribute must always have the value "URL". </message>
      </error>
      <corpusPackages>
        <package isValid="TRUE" name="IP_18000_CSIP22_1" isImplemented="TRUE">
          <path>invalid/IP_18000_CSIP22_1</path>
          <description>This package has a correct LOCTYPE-attribute value: the value "URL" </description>
        </package>
        <package isValid="FALSE" name="IP_18000_CSIP22_2" isImplemented="TRUE">
          <path>invalid/IP_18000_CSIP22_2</path>
          <description>This package has a incorrect LOCTYPE-attribute value: the value "ARK" </description>
        </package>
        <package isValid="FALSE" name="IP_18000_CSIP22_3" isImplemented="TRUE">
          <path>invalid/IP_18000_CSIP22_3</path>
          <description>This package has a incorrect LOCTYPE-attribute value: the value "DOI" </description>
        </package>
        <package isValid="FALSE" name="IP_18000_CSIP22_4" isImplemented="TRUE">
          <path>invalid/IP_18000_CSIP22_4</path>
          <description>This package has a incorrect LOCTYPE-attribute value: the value "HANDLE" </description>
        </package>
        <package isValid="FALSE" name="IP_18000_CSIP22_5" isImplemented="TRUE">
          <path>invalid/IP_18000_CSIP22_5</path>
          <description>This package has a incorrect LOCTYPE-attribute value: the value "OTHER" </description>
        </package>
        <package isValid="FALSE" name="IP_18000_CSIP22_6" isImplemented="TRUE">
          <path>invalid/IP_18000_CSIP22_6</path>
          <description>This package has a incorrect LOCTYPE-attribute value: the value "PURL" </description>
        </package>
        <package isValid="FALSE" name="IP_18000_CSIP22_7" isImplemented="TRUE">
          <path>invalid/IP_18000_CSIP22_7</path>
          <description>This package has a incorrect LOCTYPE-attribute value: the value "URN" </description>
        </package>
        <package isValid="FALSE" name="IP_18000_CSIP22_8" isImplemented="TRUE">
          <path>invalid/IP_18000_CSIP22_8</path>
          <description>This package has a incorrect LOCTYPE-attribute value: the value "url" in lowercase </description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>

=== DILCISBoard/eark-ip-test-corpus/corpus/CSIP/CSIP2/testCase.xml
<testCase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="testCase.xsd" testable="TRUE">
  <id specification="CSIP" version="2.0.3" requirementId="CSIP2"/>
  <references>
    <reference requirementId="CSIP2" URL="http://earkcsip.dilcis.eu/#CSIP2"/>
  </references>
  <requirementText>
    <name>Content Category</name>
    <location>mets/@TYPE</location>
    <description>
      The mets/@TYPE attribute MUST be used to declare the category of the content held in the package, e.g. book, journal, stereograph, video, etc.. Legal values are defined in a fixed vocabulary. When the content category used falls outside of the defined vocabulary the mets/@TYPE value must be set to “OTHER” and the specific value declared in mets/@csip:OTHERTYPE. The vocabulary will develop under the curation of the DILCIS Board as additional content information type specifications are produced.
      See also: Content Category, https://earkcsip.dilcis.eu/#VocabularyContentCategory
    </description>
    <cardinality>1..1</cardinality>
    <level>MUST</level>
  </requirementText>
  <description>
    mets/@TYPE MUST exist.
    mets/@TYPE MUST have a value from the VocabularyContentCategory as defined by DILCIS Board.
    If mets/@TYPE = “OTHER” then mets/@csip:OTHERTYPE MUST exist and have a value.
  </description>
  <dependencies>
    <dependency requirementId="VocabularyContentCategory" URL="https://earkcsip.dilcis.eu/#VocabularyContentCategory">
      https://earkcsip.dilcis.eu/schema/CSIPVocabularyContentCategory.xml
    </dependency>
  </dependencies>
  <rules>
    <rule id="1">
      <description>mets/@TYPE MUST exist.</description>
      <error level="ERROR">
        <message>
          mets/@TYPE attribute does not exist. MUST be: attribute exists and has a value.
        </message>
      </error>
      <corpusPackages>
        <package name="mets-xml_mets_TYPE_attribute_not_exist" isValid="FALSE" isImplemented="TRUE">
          <path>invalid\mets-xml_mets_TYPE_attribute_not_exist</path>
          <description>
            METS.xml file has no mets/@TYPE attribute.
          </description>
        </package>
        <package name="minimal_IP_with_1_representation" isValid="TRUE" isImplemented="TRUE">
          <path>valid\minimal_IP_with_1_representation</path>
          <description>
            Minimal IP that matches all MUST requirements.
          </description>
        </package>
      </corpusPackages>
    </rule>
    <rule id="2">
      <description>mets/@TYPE MUST have a value from the VocabularyContentCategory as defined by DILCIS Board.</description>
      <error level="ERROR">
        <message>
          mets/@TYPE attribute has incorrect value. MUST be: attribute has a value from the VocabularyContentCategory as defined by DILCIS.
        </message>
      </error>
      <corpusPackages>
        <package name="mets-xml_mets_TYPE_attribute_value_incorrect" isValid="FALSE" isImplemented="TRUE">
          <path>invalid\mets-xml_mets_TYPE_attribute_value_incorrect</path>
          <description>
            METS.xml file has mets/@TYPE = "random_string_n3ihcu63LdGb37kF7".
          </description>
        </package>
        <package name="minimal_IP_with_1_representation" isValid="TRUE" isImplemented="TRUE">
          <path>valid\minimal_IP_with_1_representation</path>
          <description>
            Minimal IP that matches all MUST requirements.
          </description>
        </package>
        <!--  Ideally, there should be a valid IP for each specific vocabulary 
              value, as this is the only certain way to test that the validator 
              accepts any one of them. This should be automated as 
              VocabularyContentCategory currently allows 25 different values. 
        <package name="valid_minimal_mets_TYPE_value_vocabulary_1" isValid="TRUE">
          <path></path>
          <description>
            Minimal IP that matches all MUST requirements, mets/@TYPE value set to VocabularyContentCategory allowed value nr 1.
          </description>
        </package>-->
      </corpusPackages>
    </rule>
    <rule id="3">
      <description>If mets/@TYPE = “OTHER” then mets/@csip:OTHERTYPE MUST exist.</description>
      <error level="ERROR">
        <message>
          mets/@csip:OTHERTYPE attribute does not exist. MUST be: If mets/@TYPE = “OTHER” then mets/@csip:OTHERTYPE MUST exist and have a value.
        </message>
      </error>
      <corpusPackages>
        <package name="mets-xml_mets_TYPE_attribute_value_OTHER_and_csip-OTHERTYPE_attribute_not_exist" isValid="FALSE" isImplemented="TRUE">
          <path>invalid\mets-xml_mets_TYPE_attribute_value_OTHER_and_csip-OTHERTYPE_attribute_not_exist</path>
          <description>
            METS.xml file has mets/@TYPE = "OTHER", mets/@csip:OTHERTYPE attribute does not exist.
          </description>
        </package>
        <package name="valid_minimal_mets_TYPE_value_OTHER" isValid="TRUE" isImplemented="TRUE">
          <path>valid\minimal_IP_with_1_representation</path>
          <description>
            Minimal IP that matches all MUST requirements, mets/@TYPE = "OTHER", mets/@csip:OTHERTYPE = "Textual works – Manuscripts".
          </description>
        </package>
      </corpusPackages>
    </rule>
    <rule id="4">
      <description>If mets/@TYPE = “OTHER” then mets/@csip:OTHERTYPE MUST exist and have a value.</description>
      <error level="ERROR">
        <message>
          mets/@csip:OTHERTYPE attribute has no value. MUST be: If mets/@TYPE = “OTHER” then mets/@csip:OTHERTYPE MUST exist and have a value.
        </message>
      </error>
      <corpusPackages>
        <package name="mets-xml_mets_TYPE_attribute_value_OTHER_and_csip-OTHERTYPE_attribute_has_no_value" isValid="FALSE" isImplemented="TRUE">
          <path>invalid\mets-xml_mets_TYPE_attribute_value_OTHER_and_csip-OTHERTYPE_attribute_has_no_value</path>
          <description>
            METS.xml file has mets/@TYPE = "OTHER", mets/@csip:OTHERTYPE = "".
          </description>
        </package>
        <package name="valid_minimal_mets_TYPE_value_OTHER" isValid="TRUE" isImplemented="TRUE">
          <path>valid\minimal_IP_with_1_representation</path>
          <description>
            Minimal IP that matches all MUST requirements, mets/@TYPE = "OTHER", mets/@csip:OTHERTYPE = "Textual works – Manuscripts".
          </description>
        </package>
      </corpusPackages>
    </rule>
  </rules>
</testCase>
